grails-app/domain/co/jefersson/prueba/Oder.groovy
package co.jefersson.prueba

import java.util.Date;
import grails.validation.Validateable

/**
 * Clase de dominio que mapea la tabla order y se utiliza para ingreso de nuevos registros
 * @author Jefersson Nuñez
 * */
@Validateable
class Oder {

	String deliveryAdress
	Integer price
	Integer quantity
	String active = 'SI' // Un usuario solo puede tener una orden activa a la vez
	
    Date dateCreated
	Date lastUpdated
	
	User customer
	
	static hasMany = [ orderDetails: OrderDetail ]
	
    static constraints = {
		deliveryAdress(nullable: false, blank: false)
		quantity max:5 // Se limita el número de pedidos en una orden por usuario
    }
	
	static mapping = {
		autoTimestamp true // Permite generar fechas automáticamente
		sort id: 'asc'
	}
}

grails-app/controllers/co/jefersson/prueba/OderController.groovy
package co.jefersson.prueba



import static org.springframework.http.HttpStatus.*

import org.springframework.stereotype.Service;

import grails.transaction.Transactional

/**
 * Clase que permite gestionar la comunicación entre la vista y el modelo para la funcionalidad de ordenes
 * @author Jefersson Nuñez
 * */
class OderController {
	
    static allowedMethods = [edit: ['GET', 'POST']]

    def index(Integer max) {
        model:[]
    }

	// Finaliza una orden
    def edit() {
		def orderInstance = Oder.findById(params.order as Long)
		if(orderInstance == null){
			render 'error@'
			render "No hay orden"
			return
		}
		
		orderInstance.active = 'NO'
		
		if(!orderInstance.save(flush:true)){
			render 'error@'
			render "No se pudo finalizar la orden"
			return
		}
		
		render 'success@'
		render "Exitoso, ya puede generar una nueva orden"
		return
    }

}

grails-app/views/oder/_listOrders.gsp
					<g:if test="${flash.message}">
						<div class="message" role="status">${flash.message}</div>
					</g:if>
					<g:if test="${oderInstanceList.empty}">
						<p id="noEntries"><g:message code="default.noEntries.label"/></p>
					</g:if>
					<g:else>
						<table class="table table-bordered table-striped">
							<thead>
								<tr>
									<th class="text-center"><g:message code="oder.dateCreated.label" /></th>
									<th class="text-center"><g:message code="oder.id.label" /></th>
									<th class="text-center"><g:message code="oder.price.label" /></th>
									<th class="text-center"><g:message code="oder.deliveryAdress.label" /></th>
									<th class="text-center"><g:message code="oder.products.label" /></th>
									<th class="text-center"></th>
								</tr>
							</thead>
							<tbody>
							<g:each in="${oderInstanceList}" status="i" var="oderInstance">
								<tr class="${(i % 2) == 0 ? 'even' : 'odd'} fil" data-id="${oderInstance.id }">
									<td><g:formatDate date="${oderInstance.dateCreated}" format="yyyy/MM/dd hh:mm a" /></td>
									<td class="text-center">${fieldValue(bean: oderInstance, field: "id")}</td>
									<td class="text-center"><g:formatNumber number="${oderInstance.price}" type="currency" currencyCode="COP" /></td>
									
									<td class="text-center">${fieldValue(bean: oderInstance, field: "deliveryAdress")}</td>
									<td class="text-center">
										<g:each in="${oderInstance.orderDetails}" status="j" var="oderDetailInstance">
											${ oderDetailInstance.quantity } x ${ oderDetailInstance.product.name } 
											<br>
										</g:each>
									</td>
									<td>
										<g:if test="${oderInstance.active == 'SI'}">
											<button class="btn btn-success btn-outline btn-end-order" 
												data-order="${oderInstance.id }" type="button" >
												Finalizar
											</button>
										</g:if>
										<g:else>
											<button class="btn btn-success btn-outline btn-end-order" disabled="disabled"
												data-order="${oderInstance.id }" type="button" >
												Finalizar
											</button>
										</g:else>
									</td>
								</tr>
							</g:each>
							</tbody>
						</table>
					</g:else>

grails-app/views/oder/index.gsp
<%@ page import="co.jefersson.prueba.Oder" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'oder.label', default: 'Oder')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<div class="row">
			<g:hiddenField id="urlBase" name="urlBase" value="${createLink(uri:'/')}" />
		    <div class="col-lg-12">
		        <div class="row">
		        	<div class="ibox float-e-margins">
	                     <div class="ibox-title">
	                         <h5><g:message code="default.orders.label" /></h5>
	                     </div>  
						 <div class="ibox-content">
	                          <div class="feed-activity-list">
	                          	
	                                 <div class="row tooltip-demo">
	                                 	<div class="col-lg-8">
	                                 		<button class="btn btn-info btn-outline" type="button" id="btn-search"
	                                 			data-toggle="tooltip" title="Llama el método list del servicio rest, la petición ajax añade las fechas inicial y final de búsqueda" data-placement="right">
	                                 			Buscar
	                                 		</button>
	                                 	</div>
	                                 	<div class="container-fluid col-lg-4 pull-right">
	                                 		
	                                 	</div>
	                                 </div>
	                                 <br>
	                                 <div id="div-content-list-orders">
	                                 	
	                                 </div>
	                                  
	                          </div>
	                     </div>
	                </div>
		        </div>
	        </div>
	       
		</div>
		<asset:javascript src="order.js" />
	</body>
</html>