grails-app/domain/co/jefersson/prueba/User.groovy
package co.jefersson.prueba

/**
 * Clase de dominio que mapea la tabla customer y se utiliza para ingreso de nuevos registros
 * @author Jefersson Nuñez
 * */
class User {
	String name
	String lastName
    String username
    String passwordHash
	
	Date dateCreated
	Date lastUpdated
    
    static hasMany = [ roles: Role, permissions: String, products:Product ] // Relaciones
	
	// Restricciones
    static constraints = {
        username(nullable: false, blank: false, unique: true)
		name(nullable: false, blank: false)
		lastName(nullable: false, blank: false)
		products nullable : true
    }
	
	static mapping = {
		version false
		table 'customer'
		id generator:'native'
		autoTimestamp true // Permite generar fechas automáticamente
	}
}

grails-app/controllers/co/jefersson/prueba/UserController.groovy
package co.jefersson.prueba



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

/**
 * Clase que permite gestionar la comunicación entre la vista y el modelo para la funcionalidad de usuarios, solo lectura
 * @author Jefersson Nuñez
 * */
@Transactional(readOnly = true)
class UserController {

    def index(Integer max) {
        respond User.list(), model:[userInstanceCount: User.count()]
    }

}

grails-app/views/user/_listUsuarios.gsp
					<g:if test="${flash.message}">
						<div class="message" role="status">${flash.message}</div>
					</g:if>
					<g:if test="${userInstanceList.empty}">
						<p id="noEntries"><g:message code="default.noEntries.label"/></p>
					</g:if>
					<g:else>
						<table class="table table-bordered table-striped">
							<thead>
								<tr>
									<th class="text-center"><g:message code="user.username.label" /></th>
									<th class="text-center"><g:message code="user.name.label" /></th>
									<th class="text-center"><g:message code="user.lastName.label" /></th>
									<th class="text-center"><g:message code="user.products.label" /></th>
								</tr>
							</thead>
							<tbody>
							<g:each in="${userInstanceList}" status="i" var="userInstance">
								<tr class="${(i % 2) == 0 ? 'even' : 'odd'} fil" data-id="${userInstance.id }">
									<td class="text-center">${fieldValue(bean: userInstance, field: "username")}</td>
									<td class="text-center">${fieldValue(bean: userInstance, field: "name")}</td>
									<td class="text-center">${fieldValue(bean: userInstance, field: "lastName")}</td>
									<td class="text-center">
										<g:each in="${userInstance?.products}" status="p" var="productInstance">
											${productInstance.name }
											<g:if test="${userInstance?.products?.size() - 1 != p }">
												-
											</g:if>
										</g:each>
									</td>
								</tr>
							</g:each>
							</tbody>
						</table>
						<div class="pagination mi-paginacion-ajax">
							<g:paginate total="${userInstanceCount ?: 0}" params="${params}"/>
						</div>
					</g:else>

grails-app/views/user/index.gsp
<%@ page import="co.jefersson.prueba.User" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<div class="row">
			<g:hiddenField id="urlBase" name="urlBase" value="${createLink(uri:'/')}" />
		    <div class="col-lg-12">
		        <div class="row">
		        	<div class="ibox float-e-margins">
	                     <div class="ibox-title">
	                         <h5><g:message code="default.users.label" /></h5>
	                     </div>  
						 <div class="ibox-content">
	                          <div class="feed-activity-list">
	                          	
	                                 <div class="row">
	                                 	
	                                 </div>
	                                 <br>
	                                 <div id="div-content-list-usuarios">
	                                 	<g:render template="listUsuarios" ></g:render>
	                                 </div>
	                                  
	                          </div>
	                     </div>
	                </div>
		        </div>
	        </div>
	       
		</div>
		
	</body>
</html>