grails-app/domain/co/jefersson/prueba/Product.groovy
package co.jefersson.prueba

import java.util.Date;

/**
 * Clase de dominio que mapea la tabla product y se utiliza para ingreso de nuevos registros
 * @author Jefersson Nuñez
 * */
class Product {
	
	String name
	Integer price
	String description
	Integer quantity
	
	Date dateCreated
	Date lastUpdated
	
	static hasMany = [ users: User ]
	static belongsTo = User

    static constraints = {
		name(nullable: false, blank: false, unique: true)
		price(nullable: false, blank: false)
		quantity(nullable: false, blank: false)
		description(nullable:true)
    }
	
	static mapping = {
		autoTimestamp true // Permite generar fechas automáticamente
		sort id: 'asc'
	}
}

grails-app/controllers/co/jefersson/prueba/ProductController.groovy
package co.jefersson.prueba



import static org.springframework.http.HttpStatus.*

import grails.transaction.Transactional
import org.apache.shiro.SecurityUtils

/**
 * Clase que permite gestionar la comunicación entre la vista y el modelo para la funcionalidad de productos, solo lectura
 * @author Jefersson Nuñez
 * */
@Transactional(readOnly = true)
class ProductController {

	//Envía a la vista el listado de productos por usuario en sesión
    def index(Integer max) {
		def userInstance = User.findByUsername(SecurityUtils.subject.principal) // Usuario en sesión
		def listProducts = userInstance.products
		flash.message = message(code: 'product.info.message')
        model:[productInstanceList:listProducts]
    }

}

grails-app/views/product/_listProducts.gsp
					<g:if test="${flash.message}">
						<div class="alert alert-info alert-dismissible div-info-product-order" role="alert">
							<button type="button" class="close" data-dismiss="alert">
								<span aria-hidden="true">&times;</span><span class="sr-only"><g:message
										code="default.button.close.label" /> </span>
							</button>
							${flash.message}
						</div>
					</g:if>
					<g:if test="${productInstanceList.empty}">
						<p id="noEntries"><g:message code="default.noEntries.label"/></p>
					</g:if>
					<g:else>
						<table class="table table-bordered table-striped">
							<thead>
								<tr>
									<th class="text-center"><g:message code="product.name.label" /></th>
									<th class="text-center"><g:message code="product.price.label" /></th>
									<th class="text-center"><g:message code="product.quantity.label" /></th>
									<th class="text-center"><g:message code="prouct.description.label" /></th>
									<th class="text-center"></th>
								</tr>
							</thead>
							<tbody>
							<g:each in="${productInstanceList}" status="i" var="productInstance">
								<tr class="${(i % 2) == 0 ? 'even' : 'odd'} fil" data-id="${productInstance.id }">
									<td class="text-center">${fieldValue(bean: productInstance, field: "name")}</td>
									<td class="text-center">${fieldValue(bean: productInstance, field: "price")}</td>
									<td class="text-center">${fieldValue(bean: productInstance, field: "quantity")}</td>
									<td class="text-center">${fieldValue(bean: productInstance, field: "description")}</td>
									<td class="text-center">
										<button class="btn btn-success btn-outline btn-add-product" data-quantity="${productInstance.quantity }"
											data-name="${productInstance.name }" data-product="${productInstance.id }" type="button" id="btn-add-product">
											<i class="fa fa-plus"></i>
										</button>
									</td>
								</tr>
							</g:each>
							</tbody>
						</table>
						<div class="pagination mi-paginacion-ajax">
							<g:paginate total="${productInstanceCount ?: 0}" params="${params}"/>
						</div>
					</g:else>

grails-app/views/product/index.gsp
<%@ page import="co.jefersson.prueba.Product" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'product.label', default: 'Product')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<div class="row">
			<g:hiddenField id="urlBase" name="urlBase" value="${createLink(uri:'/')}" />
		    <div class="col-lg-12">
		        <div class="row">
		        	<div class="ibox float-e-margins">
	                     <div class="ibox-title">
	                         <h5><g:message code="default.products.label" /></h5>
	                     </div>  
						 <div class="ibox-content">
	                          <div class="feed-activity-list">
	                          	
	                                 <div class="row">
	                                 	
	                                 </div>
	                                 <br>
	                                 <div id="div-content-list-products">
	                                 	<g:render template="listProducts" ></g:render>
	                                 </div>
	                                  
	                          </div>
	                     </div>
	                </div>
		        </div>
	        </div>
	       
		</div>
		
		<!-- Modal Agrega Producto -->
		<div class="modal inmodal" id="modal-add-product" tabindex="-1"
			role="dialog" aria-labelledby="myModalLabel">
			<div class="modal-dialog modal-lg" role="document">
				<form name="form-add-product" id="form-add-product" >
					<div class="modal-content">
				
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						</button>
						<h4 class="modal-title" id="myModalLabel"><g:message code="product.title.label"/></h4>
					</div>
					
					<div class="modal-body form-horizontal">
						
						<div id="div-form-product">
						
							<div class="form-group required" id="div-delivery-adress">
								<label for="nombre" class="col-sm-4 control-label field-required">
									<g:message code="order.deliveryAdress.label" default="Dirección" />
									<span class="text-danger">*</span>
								</label>
								<div class="col-sm-8">
									<g:textField name="deliveryAdress" id="deliveryAdress" class="input-sm col-xs-10 col-sm-10"  required="" />
								</div>
							</div>
							
							<div class="form-group required">
								<label for="formOrder" class="col-sm-4 control-label field-required">
									<g:message code="product.quantity.label"/>
									<span class="text-danger">*</span>
								</label>
								<div class="col-sm-8">
									<g:field type="number" min="1" id="quantity" name="quantity" class="input-sm col-xs-10 col-sm-10" required="" />
								</div>	
							</div>
							
						</div>
						
						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-white btn-modal-cerrar" data-dismiss="modal">
								<g:message code="default.cancel.label" />
							</button>
							<button type="submit" class="btn btn-primary btn-guardar-modal">
								<g:message code="default.add.product.label" />
							</button>
						</div>
					
					</div>
				</form>
			</div>
		</div>
		<asset:javascript src="product.js" />
	</body>
</html>